title: "[项目想法] "
labels: ["project-idea"]

body:
  - type: markdown
    attributes:
      value: |
        请认真填写下面的信息。

        这里提交的是“项目想法”， 可以是一个完整项目，也可以是一个具体问题的改进想法
        例如：修复 OJ 系统搜索框二次搜索失效问题。

  - type: input
    id: idea-name
    attributes:
      label: 想法名称
      description: 写出你的项目名称。
      placeholder: 例如：修复 OJ 系统搜索框二次搜索失效问题
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: 一句话概括
      description: 用一句话说明这个想法主要想做什么。
      placeholder: 例如：修复 OJ 系统中搜索框第一次搜索正常、第二次再次搜索时失效的问题，提升题目检索体验。
    validations:
      required: true

  - type: dropdown
    id: direction
    attributes:
      label: 项目方向
      description: 请选择这个想法大致属于哪一类。
      options:
        - ACM / XCPC 训练辅助
        - OJ / 题单 / 排名榜
        - 社团管理工具
        - 知识库 / 文档建设
        - 网站 / 前端 / 后端
        - Bug 修复 / 功能优化
        - 项目重构
        - 其他
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 你想解决什么问题？
      description: 请说明目前存在的问题，以及为什么值得解决。
      placeholder: |
        例如：

        目前 OJ 系统的搜索框在第一次输入关键词并搜索时可以正常返回结果，
        但当用户进入二级页面再次返回到该页面时，搜索功能会失效，可能表现为没有反应、结果不刷新，
        或者仍然停留在第一次搜索结果。

        这个问题会影响用户查找题目的效率，尤其是在训练时需要频繁搜索题号、题目名称、
        标签或关键词。如果不修复，用户可能需要刷新页面后才能再次搜索，使用体验较差。
    validations:
      required: true


  - type: dropdown
    id: difficulty
    attributes:
      label: 预估难度
      description: 你认为这个想法实现起来大概有多难？
      options:
        - 简单
        - 简单到中等
        - 中等
        - 中等到困难
        - 困难
        - 暂不确定
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: 类似项目或参考资料
      description: 可以填写相关链接、截图说明、已有功能参考等。如果没有，可以写“暂无”。
      placeholder: |
        例如：

        可以参考当前 OJ 系统中其他正常工作的搜索功能，
        例如题单搜索、用户搜索或后台管理搜索。

        也可以参考常见 Web 搜索框的实现方式：
        输入关键词后重新发送请求，并根据最新返回结果更新页面。
    validations:
      required: false

  - type: textarea
    id: discussion
    attributes:
      label: 希望大家讨论的问题
      description: 你希望其他成员重点帮你判断或补充哪些问题？
      placeholder: |
        例如：

        1. 这个问题是所有浏览器都会出现，还是只在部分浏览器中出现？
        2. 搜索失效时，控制台是否有报错？
        3. 第二次搜索时，Network 里是否真的发出了新的请求？
        4. 搜索结果不刷新，是前端没有重新渲染，还是后端返回了错误数据？
        5. 是否需要顺便优化搜索框的交互体验？
    validations:
      required: false

  - type: checkboxes
    id: confirm
    attributes:
      label: 提交前确认
      options:
        - label: 我已经检查过目前没有同学提出类似的项目
          required: true
        - label: 我确认这个想法不涉及作弊、外挂、恶意爬取、账号盗用或其他违规内容。
          required: true
        - label: 我理解这个想法不一定会被直接立项，最终会结合投票、讨论和可实现性综合判断。
          required: true
